name: clone submodules

on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
            description: 'build scenario tag'  
            
permissions: write-all

jobs:
  clone-submodules:
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MichaelGrafnetter/DSInternals
          path: DSInternals
      - uses: actions/checkout@v2
      - run: |
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/MichaelGrafnetter/DSInternals.git DSInternals
          git add .
          git commit -m "add submodule DSInternals"
          git push
        continue-on-error: true 
       
      - uses: actions/checkout@v2
        with:
          repository: sqlmapproject/sqlmap
          path: sqlmap
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/sqlmapproject/sqlmap.git sqlmap
          git add .
          git commit -m "add submodule sqlmap"
          git push
        continue-on-error: true 
        
      - uses: actions/checkout@v2
        with:
          repository: SnaffCon/Snaffler
          path: Snaffler
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/SnaffCon/Snaffler.git
          git add .
          git commit -m "add submodule Snaffler"
          git push
        continue-on-error: true
        
      - uses: actions/checkout@v2
        with:
          repository: bitsadmin/wesng
          path: wesng
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/bitsadmin/wesng.git
          git add .
          git commit -m "add submodule wesng"
          git push
        continue-on-error: true

      - uses: actions/checkout@v2
        with:
          repository: wagga40/Zircolite
          path: Zircolite
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/wagga40/Zircolite.git
          git add .
          git commit -m "add submodule Zircolite"
          git push
        continue-on-error: true
      
      - uses: actions/checkout@v2
        with:
          repository: VirusTotal/yara
          path: yara
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/VirusTotal/yara.git
          git add .
          git commit -m "add submodule yara"
          git push
        continue-on-error: true
        
      - uses: actions/checkout@v2
        with:
          repository: 0x6d69636b/windows_hardening
          path: windows_hardening
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/0x6d69636b/windows_hardening.git
          git add .
          git commit -m "add submodule windows_hardening"
          git push
        continue-on-error: true

      - uses: actions/checkout@v2
        with:
          repository: liranpi2/limiter
          path: limiter
      - uses: actions/checkout@v2
      - run: | 
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule add https://github.com/liranpi2/limiter.git
          git add .
          git commit -m "add submodule limiter"
          git push
        continue-on-error: true
