name: GitHub Actions - update submodule
on:
  workflow_dispatch:
    inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
          tags:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
        run: |
          git config user.name liranpi2
          git pull --recurse-submodules
          git submodule update --remote --recursive
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
